# permissions for end users to view slothhelpers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slothhelper-viewer-role
rules:
- apiGroups:
  - op-practice-1.databasedsolution.io
  resources:
  - slothhelpers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - op-practice-1.databasedsolution.io
  resources:
  - slothhelpers/status
  verbs:
  - get
